In [5]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("../data/employees.csv")
df

,name,age,department,salary
0,Teja,22.0,IT,55000
1,Rahul,25.0,HR,45000
2,Priya,28.0,Finance,60000
3,Arjun,NaN,IT,50000
4,Rahul,25.0,HR,45000
5,Sneha,30.0,NaN,65000


In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   name        6 non-null      str    
 1   age         5 non-null      float64
 2   department  5 non-null      str    
 3   salary      6 non-null      int64  
dtypes: float64(1), int64(1), str(2)
memory usage: 324.0 bytes


In [4]:
df.isnull().sum()

name          0
age           1
department    1
salary        0
dtype: int64

In [5]:
df["age"] = df["age"].fillna(df["age"].mean())
df["department"] = df["department"].fillna("Unknown")

df

,name,age,department,salary
0,Teja,22.0,IT,55000
1,Rahul,25.0,HR,45000
2,Priya,28.0,Finance,60000
3,Arjun,26.0,IT,50000
4,Rahul,25.0,HR,45000
5,Sneha,30.0,Unknown,65000


In [6]:
df = df.drop_duplicates().reset_index(drop=True)
df

,name,age,department,salary
0,Teja,22.0,IT,55000
1,Rahul,25.0,HR,45000
2,Priya,28.0,Finance,60000
3,Arjun,26.0,IT,50000
4,Sneha,30.0,Unknown,65000


In [7]:
df.groupby("department")["name"].count()

department
Finance    1
HR         1
IT         2
Unknown    1
Name: name, dtype: int64

In [8]:
df.groupby("department")["salary"].mean()

department
Finance    60000.0
HR         45000.0
IT         52500.0
Unknown    65000.0
Name: salary, dtype: float64

In [9]:
import numpy as np

print(np.__version__)

2.5.2


In [6]:
arr = np.array([10, 20, 30, 40, 50])
arr

array([10, 20, 30, 40, 50])

In [7]:
arr.ndim

1

In [8]:
arr + 5

array([15, 25, 35, 45, 55])

In [9]:
arr[0]

np.int64(10)

In [10]:
arr + 5

array([15, 25, 35, 45, 55])

In [11]:
pd.__version__

'3.0.5'

In [12]:
data = {
    "Name": ["Teja", "Rahul", "Priya"],
    "Age": [22, 25, 28]
}

df = pd.DataFrame(data)
df

,Name,Age
0,Teja,22
1,Rahul,25
2,Priya,28


In [13]:
df = pd.read_csv("../data/employees.csv")
df

,name,age,department,salary
0,Teja,22.0,IT,55000
1,Rahul,25.0,HR,45000
2,Priya,28.0,Finance,60000
3,Arjun,NaN,IT,50000
4,Rahul,25.0,HR,45000
5,Sneha,30.0,NaN,65000


In [14]:
high_salary = df[df["salary"] > 50000]
high_salary

,name,age,department,salary
0,Teja,22.0,IT,55000
2,Priya,28.0,Finance,60000
5,Sneha,30.0,NaN,65000


In [15]:
df.sort_values("salary", ascending=False)

,name,age,department,salary
5,Sneha,30.0,NaN,65000
2,Priya,28.0,Finance,60000
0,Teja,22.0,IT,55000
3,Arjun,NaN,IT,50000
1,Rahul,25.0,HR,45000
4,Rahul,25.0,HR,45000


In [16]:
df.isnull().sum()

name          0
age           1
department    1
salary        0
dtype: int64

In [17]:
df["age"] = df["age"].fillna(df["age"].mean())
df["department"] = df["department"].fillna("Unknown")
df

,name,age,department,salary
0,Teja,22.0,IT,55000
1,Rahul,25.0,HR,45000
2,Priya,28.0,Finance,60000
3,Arjun,26.0,IT,50000
4,Rahul,25.0,HR,45000
5,Sneha,30.0,Unknown,65000


In [18]:
df.duplicated().sum()

np.int64(1)

In [19]:
df = df.drop_duplicates().reset_index(drop=True)
df

,name,age,department,salary
0,Teja,22.0,IT,55000
1,Rahul,25.0,HR,45000
2,Priya,28.0,Finance,60000
3,Arjun,26.0,IT,50000
4,Sneha,30.0,Unknown,65000


In [20]:
df.groupby("department")["name"].count()

department
Finance    1
HR         1
IT         2
Unknown    1
Name: name, dtype: int64

In [21]:
df.groupby("department")["salary"].agg(["count", "mean", "min", "max"])

,count,mean,min,max
department,,,,
Finance,1,60000.0,60000,60000
HR,1,45000.0,45000,45000
IT,2,52500.0,50000,55000
Unknown,1,65000.0,65000,65000


In [22]:
managers = pd.DataFrame({
    "department": ["IT", "HR", "Finance", "Unknown"],
    "manager": ["Ravi", "Anil", "Kiran", "Unassigned"]
})

df.merge(managers, on="department", how="left")

,name,age,department,salary,manager
0,Teja,22.0,IT,55000,Ravi
1,Rahul,25.0,HR,45000,Anil
2,Priya,28.0,Finance,60000,Kiran
3,Arjun,26.0,IT,50000,Ravi
4,Sneha,30.0,Unknown,65000,Unassigned


In [23]:
df.describe()

,age,salary
count,5.00000,5.00000
mean,26.20000,55000.00000
std,3.03315,7905.69415
min,22.00000,45000.00000
25%,25.00000,50000.00000
50%,26.00000,55000.00000
75%,28.00000,60000.00000
max,30.00000,65000.00000


In [24]:
df = pd.read_csv("../data/employees.csv")

df["age"] = df["age"].fillna(df["age"].mean())
df["department"] = df["department"].fillna("Unknown")

df = df.drop_duplicates().reset_index(drop=True)

df.to_csv("../data/employees_clean.csv", index=False)

df

,name,age,department,salary
0,Teja,22.0,IT,55000
1,Rahul,25.0,HR,45000
2,Priya,28.0,Finance,60000
3,Arjun,26.0,IT,50000
4,Sneha,30.0,Unknown,65000


In [25]:
pd.read_csv("../data/employees_clean.csv")

,name,age,department,salary
0,Teja,22.0,IT,55000
1,Rahul,25.0,HR,45000
2,Priya,28.0,Finance,60000
3,Arjun,26.0,IT,50000
4,Sneha,30.0,Unknown,65000
